### ISSUE TITLE
Documentation for hb_ColorIndex() is lacking

### ISSUE THREAD

**Issue by mlacecilia** [Petewg/harbour-core#12]

**Comment by Petewg** [comment]
Hi Maurizio,
Indeed, documentation for this (and other) function(s) is missing; thanks for pointing it out. 
I'll try to add something soon ("as soon as possible", that is). 
In the meantime, you are very welcome to offer your contribution. ;-)

regards,
Pete

**Comment by mlacecilia** [comment]
Hi Pete,
I'm opening issues just as a memo, because I'm currently busy.
I'll try to contribute ASAP.
Best regards.
--
Maurizio

Il mer 9 feb 2022, 08:15 Pete ***@***.***> ha scritto:

**Comment by mlacecilia** [comment]
Just added
