### ISSUE TITLE
hb_gcStep

### ISSUE THREAD

**Issue by ghost** [Petewg/harbour-core#14]
The `hb_gcStep` function is a function in the Harbour language that is used to perform a single step of the garbage collection process. Garbage collection is a process that is used to reclaim memory that is no longer being used by the program.

The `hb_gcStep` function is called automatically by the Harbour runtime system when necessary, but it can also be called manually if desired. For example, you might call hb_gcStep if you want to manually control the garbage collection process or if you want to perform garbage collection at a specific point in your code.

The `hb_gcStep` function takes no arguments and returns a logical value indicating whether garbage collection was performed. If garbage collection was performed, the function returns `.T.` (true). If garbage collection was not performed, the function returns `.F.` (false).

Here is an example of how you might use the `hb_gcStep` function in a Harbour program:
```
DO WHILE hb_gcStep()
   // Do something while garbage collection is being performed
ENDDO
```

In this example, the `hb_gcStep` function is called in a loop until it returns `.F.`, indicating that garbage collection has completed. The code inside the loop will be executed repeatedly while garbage collection is in progress.

https://github.com/harbour/core/blob/master/src/vm/garbage.c#L758

**Comment by Petewg** [comment]
Hello Rafal,
many thanks for you contributions!
I've added doc for <b>hb_gcStep()</b>  based on your description above.
Regarding  <i>hb_keyChar()</i> I'm not sure the doc you posted corresponds to this function. I think it needs revision.
Now, as for <i>hb_BeginObject()</i>, well the Object Oriented chapter of Harbour is almost "terra incognita" for me so I don't know how to incorporate it in this wiki and besides this, I'm out of time this season to open a new page dedicated on OO  part of Harbour.
If you want, I could add You in <b>collaborators,</b> so you'll have write access and be able to add doc content directly by yourself.
Just let me know if you're interested.

my best wishes for new year 2023!

regards,
Pete

**Comment by rjopek** [comment]
Hello Pete,

In this way, I tried to mark my presence at the end of the year in Harbor. I don't think it's a good idea, and my critical attitude towards parts of the Harbor project still hasn't changed.

My best wishes for new year 2023!

Kind regards
--Rafał
