### ISSUE TITLE
hb_keyChar

### ISSUE THREAD

**Issue by ghost** [Petewg/harbour-core#15]
The `hb_keyChar` function is a function in the Harbour language that is used to retrieve the character code of the last key pressed by the user. It can be used to detect which keys the user is pressing in a console or GUI application.

The `hb_keyChar` function takes no arguments and returns an integer value representing the character code of the last key pressed. The character code is a number that represents the ASCII code or Unicode value of the key. For example, the character code for the letter "A" is 65, and the character code for the number "1" is 49.

Here is an example of how you might use the `hb_keyChar` function in a Harbour program:

```
LOCAL cKey

cKey := hb_keyChar()

IF cKey = K_ESC
   // The user pressed the Escape key
ELSEIF cKey = K_F1
   // The user pressed the F1 key
ELSE
   // The user pressed a different key
ENDIF
```

In this example, the `hb_keyChar` function is used to detect which key the user has pressed. If the user pressed the Escape key (character code 27), the code inside the first `IF` block will be executed. If the user pressed the F1 key (character code 112), the code inside the second `IF` block will be executed. If the user pressed a different key, the code inside the `ELSE` block will be executed.

https://github.com/harbour/core/blob/master/src/rtl/inkey.c#L232

**Comment by Petewg** [comment]
I think you probably are referring to <b>hb_keyLast()</b>
The `hb_keyChar(<nKeyCode>)` returns the character designated by the passed <i>`<nKeyCode>`</i> parameter.

**Comment by rjopek** [comment]
The implementation of the [hb_keyChar](https://github.com/harbour/core/blob/master/src/rtl/inkey.c#L232) function shown in the code you provided uses the `hb_inkeyKeyString` function to retrieve the character code of the last key pressed and stores it in the `szKeyChr` array. The `hb_inkeyKeyString` function takes three arguments:

1.An integer value representing the type of the key being pressed.
2. A character array where the key string will be stored.
3. The size of the character array.

The `hb_inkeyKeyString` function returns the length of the key string that was stored in the character array.

The `hb_keyChar` function then uses the `hb_retclen` function to return the key string as a character string to the caller. The `hb_retclen` function takes two arguments:

1. The character array containing the key string.
2. The length of the key string.

The `hb_keyChar` function therefore returns the character code of the last key pressed as a character string to the caller.

**Comment by Petewg** [comment]
Now I 'm a little confused. 
Although, I'm not a C expert, (just I try learning to read and understand harbour sources)
I cannot confirm your point. I tried your sample you posted in the first message but did not work. then i modified it to make it run, including a wait state (inkey(0)) to get the chance to press a key but still cannot confirm that it " returns the character code of the last key pressed as a character string to the caller.", as you point.
Anyway, I would be thankful if you could prepare a working sample to show the functionality you describe.

And if you're currently busy, please take your time and post it next year! ;-)

**Comment by rjopek** [comment]
> Myślę, że prawdopodobnie odnosisz się do hb_keyLast() Zwraca `hb_keyChar(<nKeyCode>)`znak wyznaczony przez przekazany `<nKeyCode>`parametr.

You are completely and 100% correct, writing documentation on New Year's Eve is not the right time, the error is entirely on my side. I'm just wondering why the Harbor developers didn't allow the `hb_keyChar` function to return a string?
